### ISSUE TITLE
Incorrect pasing of 4-byte utf-8 characters from python3 to java, and vice-versa.

### ISSUE THREAD

**Issue by rene-bakker-it** [originell/jpype#278]
The upper-bytes of a string containing characters that occupy a 4-byte space in utf-8 may be changed/removed when passing from Python to Java.

I stumbled upon it when transferring emoji characters with JayDeBeApi. I did not find any reference to this issue, so I hope I am not duplicating anything. In any case it seems to marginal since it only affects emoji characters and there is a work-around.

**Remarks:**
- The issue has NOT been tested with python2 (only 3.5)
- The issue has only been checked on a linux system
- Tests with JPype 0.6.2 and Java 1.8.151

### From Python to Java

When passing strings from Python to Java the upper bytes get mixed up. Examples:

 1. 😁 0xF09F9881 ->  0xEF9881
 2. 😂 0xF09F9882 ->  0xEF9882
 3. 😃 0xF09F9883 ->  0xEF9883
 4. 😄 0xF09F9884 ->  0xEF9884
 5. 😅 0xF09F9885 ->  0xEF9885

This does not happen when the strings are transfered as binary:

        String = JPackage('java').lang.String
        java_string = String("😁".encode(),'UTF8')

In such a case the string is passed correctly.

### From Java to Python

Passing of emoji characters from Java to Python3 will throw a UnicodeEncodeError (surrogates not allowed) when you try to use the generated string in python (e.g., in a print statement). The error may be avoided using:

        string_from_java = string_from_java.encode('utf-16', errors='surrogatepass').decode('utf-16')

#### Attachment

I've singled-out the issue in a small test-project.

The Java-class (JavaPrint) can receive a string from python and either print it directly to the stdout, or send it back to Python. It also contains a few standard strings, which can be called with in integer index, and then transfered to Python.

The Python file (test_javaprint.py) starts a JVM and then calls JavaPrint in different ways. Most significant is the one where a Python string is passed through Java and then compared with the original. Output is like:

        test_upload()
        ..................................................................................................
        Upload the strings stored in TDICT in JavaPrint and verify they remain the same on retrieval.
        Use surrogate encoding if printing of strings fails.
        ..................................................................................................
        english   : OK   nc =  39, nb =  39 (I can eat glass and it doesn't hurt me.)
        french    : OK   nc =  47, nb =  48 (Je peux manger du verre, ça ne me fait pas mal.)
        rune      : OK   nc =  39, nb =  97 (ᛖᚴ ᚷᛖᛏ ᛖᛏᛁ ᚧ ᚷᛚᛖᚱ ᛘᚾ ᚦᛖᛋᛋ ᚨᚧ ᚡᛖ ᚱᚧᚨ ᛋᚨᚱ)
        cn_simp   : OK   nc =  44, nb = 128 (人人生而自由,在尊严和权利上一律平等。他们赋有理性和良心,并应以兄弟关系的精神互相对待。)
        cn_trad   : OK   nc =  44, nb = 132 (人人生而自由﹐在尊嚴和權利上一律平等。他們賦有理性和良心﹐並應以兄弟關係的精神互相對待。)
        arab      : OK   nc =  40, nb =  71 (أنا قادر على أكل الزجاج و هذا لا يؤلمني.)
        emoji     : FAIL nc =  60, nb = 168 (8⃣9⃣7⃣6⃣1⃣0)
                 REF: nc =  60, nb = 217 (😁😂😃😄😅😆😠😡😢😣😤😥😨😩😪🚉🚌🚏🚑🚒🚓🚕🚗🚙🚚🚢🚤🚥🚧🚨🚻🚼🚽🚾🛀🆕🆖🆗🆘🆙🆚🈁🈂🈚🈯🈹🈺🉐🉑8⃣9⃣7⃣6⃣1⃣0)
        FAIL COUNT: 1

[unicode.tar.gz](https://github.com/originell/jpype/files/1582914/unicode.tar.gz)

**Comment by marscher** [comment]
Thank you for this detailed report. Are you using the numpy enabled version, eg. who did you install jpype?

**Comment by rene-bakker-it** [comment]
originally it was installed as part of JayDeBeApi (pip install JayDeBeApi). Because of your email, I've made a fresh install and obtained similar results:

    virtualenv -p /usr/bin/python3 --no-site-packages ~/python/jpype
    pip install JPype1

    pip freeze

        JPype1==0.6.2
        pkg-resources==0.0.0

Hence, I numpy was not enabled. If I add it, it does not make a difference.

**Comment by Thrameos** [comment]
Can we promote his code to a formal test?  I have analyzed the issue and it is clear where the problem is coming from.  Java uses a non standard encoding for 4 byte unicode strings.  Thus all the code that goes to a from JCharArray will fail to properly encode with 4 byte unicode.  If you go to and from with char* and a specified encoding (UTF-8) then the java preforms the encoding work.  

We can solve this at the base layer by pushing strings in and out using char*.  But the python2 and python3 have very different concepts of strings so we will need to update for each of the cases and test them thoroughly.

**Comment by alyaxey** [comment]
Related problem: this code crashes on windows 10 with heap corrupted code (0xC0000374)

```
import jpype
jpype.startJVM(jpype.getDefaultJVMPath())
jpype.JString('\U0001d5e6' * 2000)
```

**Comment by Thrameos** [comment]
Okay I implemented an encoder that converts from python encoded UTF8 to java encoded modified UTF8.   I am also disabling all of the codes that try to bypass from python UTF-16 to jchar as none of those paths are  checked against valid codes.  Unfortunately these are all on my experimental branch that I am working to get back to a running state.  Usual problems when doing a big rearranging of code, too many references, to few references, accessing something before it is constructed, etc.

I will add that test to my evaluation.  Hopefully the move to force encoding between the layers will address the issue.  My coworker feels this is a high importance because without it he can't use '\u01F4A9'.

**Comment by Thrameos** [comment]
This has not fallen through the cracks.  I have a fix in my rework, but it is going slowly.

**Comment by Thrameos** [comment]
This has been included in rework for #334  but we need a test case.

**Comment by rene-bakker-it** [comment]
It was not clear to me if this work is included in release 0.6.3. Hence, I just used the code attached to the original post as test. This time with python 3.6.5 and 3.5.2 in combination with Oracle/Java 1.8.0_171 and OpenJdk 10.0.1 (virtualenv, no site packages, Linux Mint 19 server). 

There was no change as compared to version 0.6.2: 
* string transfer of 4-byte utf8 failed (pass a python string directly into a Java method)
* binary transfer is OK:
      JavaPrint = JPackage('com').example.JavaPrint
      String = JPackage('java').lang.String
      jp = JavaPrint(String('😁😂😃😄😅😆😠😡😢'.encode(),'UTF8'))

     with: public JavaPrint(String myinput) { ..... }

If you like me to run a different version, please let me know. E.g., by installing a development version of JPype.

Alternatively it should be possible to run the original attachment as test (requires gradle + JPype1):
- run 'gradle jar' in the root of the project
- switch to the directory './src/main/python' and run 'test_javaprint.py'

**Comment by Thrameos** [comment]
The unicode rework is currently in version 0.7.0 which is in Thrameos/jpype on the devel branch.  Unfortunately marcher is currently busy so that has yet to hit the main repo.  If you can submit a pull request to this repo adding a set of tests for each of the calls you need to have work to `test/jpypetest/` and `test/harness/jpype` then I can merge those tests into the devel branch and make sure it is working in the next release.  It would also help because CI testing will make sure that it works on all architectures rather than just my machine.

The development branch handles all strings by encoding to utf8 converting from java modified to regular then reencoding back to unicode.  The only path that does not get this conversion treatment is direct conversion from a char[].  

If you can't make the test cases it is okay, it will hit my list sometime after numpy.array conversion which I need for my production.

**Comment by rene-bakker-it** [comment]
Created a pull-request #337 from the development branch. If desired I can run the test local when a pre-release of 0.7.0 becomes available.

**Comment by Thrameos** [comment]
This is should now be resolved in the devel branch.

**Comment by passerbythesun** [comment]
python string with `\u0000 \u0014` still don't work, but emoji is OK. use 
```
String = JPackage('java').lang.String
java_string = String("😁".encode(),'UTF8')
```
still works

**Comment by Thrameos** [comment]
Java requires a special encoding of `\u0000`

**Comment by rene-bakker-it** [comment]
I just tried using JPype v0.7.5 in combination with JayDeBeApi v1.2.3 and a MySQL database in utf8mb4 character encoding (jdbc connection with mysql-connector-java-8.0.21.jar)

All works perfect! 

Thank you.
